import pandas as pd

def generate_reasoning(row: pd.Series) -> str:
    """
    Generates a dynamic, LLM-free reasoning string based on the candidate's 
    mathematical L2 multipliers.
    
    Args:
        row: A single Pandas Series representing a candidate's features and scores.
        
    Returns:
        A formatted 1-2 sentence string explaining why they ranked highly.
    """
    
    # 1. Base Reasoning: Start with their semantic score and experience
    score = round(row.get('final_score', 0) * 100, 1)
    exp = row.get('years_of_experience', 0)
    
    reasoning = f"Strong semantic match (Score: {score}) with {exp} years of experience."
    
    # 2. Dynamic Behavioral Additions
    # We check the multipliers generated by our Scorer to see what boosted them
    
    # Notice Period (If their multiplier is > 0.9, they have a very short notice period)
    if row.get('notice_mult', 0) > 0.9:
        reasoning += " Available to join almost immediately."
        
    # GitHub Activity (If their multiplier is > 1.05, they are highly active)
    if row.get('github_mult', 1.0) > 1.05:
        gh_score = row.get('github_activity_score', 'N/A')
        reasoning += f" Exceptional open-source presence (GitHub score: {gh_score})."
        
    # Recruiter Response Rate
    if row.get('response_mult', 0) > 1.0:
        reasoning += " Highly responsive to recruiter outreach."
        
    # Open to Work
    if row.get('open_to_work_flag', False):
        reasoning += " Actively looking for new opportunities."
        
    return reasoning.strip()

def format_submission_df(df: pd.DataFrame) -> pd.DataFrame:
    """
    Cleans up the final DataFrame to strictly match the Hackathon Submission rules.
    Requires columns: candidate_id, rank, score, reasoning
    """
    # Create the rank column (1 to 100)
    df = df.copy()
    df.reset_index(drop=True, inplace=True)
    df['rank'] = df.index + 1
    
    # Ensure final_score is renamed to score
    if 'final_score' in df.columns:
        df = df.rename(columns={'final_score': 'score'})
        
    # Select ONLY the exact 4 columns requested by the judges
    submission_columns = ['candidate_id', 'rank', 'score', 'reasoning']
    return df[submission_columns]