import pandas as pd

def generate_reasoning(row: pd.Series) -> str:
    """
    Generates a dynamic, LLM-free reasoning string based on the candidate's 
    mathematical L2 multipliers.
    
    Inspects all 14 behavioral multipliers and dynamically assembles a
    1-3 sentence explanation of why the candidate ranked highly (or lowly).
    
    Args:
        row: A single Pandas Series representing a candidate's features and scores.
        
    Returns:
        A formatted reasoning string explaining their ranking position.
    """
    
    # 1. Base Reasoning: Start with their semantic score and experience
    score = round(row.get('final_score', 0) * 100, 1)
    exp = row.get('years_of_experience', 0)
    
    reasoning = f"Strong semantic match (Score: {score}) with {exp} years of experience."
    
    # 2. Dynamic Behavioral Additions
    # We check the multipliers generated by our Scorer to see what boosted them
    
    # Notice Period (If their multiplier is > 0.9, they have a very short notice period)
    if row.get('notice_mult', 0) > 0.9:
        reasoning += " Available to join almost immediately."
        
    # GitHub Activity (If their multiplier is > 1.05, they are highly active)
    if row.get('github_mult', 1.0) > 1.05:
        gh_score = row.get('github_activity_score', 'N/A')
        reasoning += f" Exceptional open-source presence (GitHub score: {gh_score})."
        
    # Recruiter Response Rate
    if row.get('response_mult', 0) > 1.0:
        reasoning += " Highly responsive to recruiter outreach."
        
    # Open to Work
    if row.get('open_to_work_flag', False):
        reasoning += " Actively looking for new opportunities."

    # Skill Assessment Competency
    if row.get('assessment_mult', 1.0) > 1.10:
        avg_score = row.get('avg_assessment_score', 'N/A')
        reasoning += f" Scored exceptionally on platform assessments ({avg_score}/100)."
    
    # Education Tier
    edu_tier = row.get('education_tier', 'unknown')
    if edu_tier == 'tier_1':
        reasoning += " Graduate of a top-tier institution."
    elif edu_tier == 'tier_2':
        reasoning += " Strong academic pedigree."
    
    # Certifications
    cert_count = row.get('certifications_count', 0)
    if cert_count >= 3:
        reasoning += f" Holds {cert_count} professional certifications."
    elif cert_count >= 1:
        reasoning += " Has relevant certifications."
    
    # Interview Reliability
    if row.get('interview_mult', 1.0) > 1.0:
        reasoning += " Reliable interview attendance record."
    
    # Market Demand
    if row.get('demand_mult', 1.0) > 1.05:
        reasoning += " High recruiter demand in the last 30 days."
        
    return reasoning.strip()

def format_submission_df(df: pd.DataFrame) -> pd.DataFrame:
    """
    Cleans up the final DataFrame to strictly match the Hackathon Submission rules.
    Requires columns: candidate_id, rank, score, reasoning
    """
    # Create the rank column (1 to 100)
    df = df.copy()
    df.reset_index(drop=True, inplace=True)
    df['rank'] = df.index + 1
    
    # Ensure final_score is renamed to score
    if 'final_score' in df.columns:
        df = df.rename(columns={'final_score': 'score'})
        
    # Select ONLY the exact 4 columns requested by the judges
    submission_columns = ['candidate_id', 'rank', 'score', 'reasoning']
    return df[submission_columns]